La-Suela-Carrito-de-Compras-master/LaSuela_CodigoFuente/TrabajoFinalWeb/Models/Empleado.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabajoFinalWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Pedidoes = new HashSet<Pedido>();
        }

        [DisplayName("Nombre de Usuario")]
        public string ID { get; set; }
        public string Contraseña { get; set; }
        public int IdTipoEmpleado { get; set; }
        [DisplayName("Nombre Completo")]
        public string Nombre { get; set; }
        [DisplayName("Numero de Celular")]
        public int Celular { get; set; }
        [DisplayName("Correo Electronico")]
        public string Correo { get; set; }
        public string Direccion { get; set; }
        public decimal Sueldo { get; set; }
    
        public virtual TipoEmpleado TipoEmpleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido> Pedidoes { get; set; }
    }
}

La-Suela-Carrito-de-Compras-master/LaSuela_CodigoFuente/TrabajoFinalWeb/Controllers/EmpleadosController.cs
using Hotel_UPC.Authorization;
using Restaurante.Constantes;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using TrabajoFinalWeb.Models;

namespace TrabajoFinalWeb.Controllers
{
    [UserLoggedOn]
    [AdminsOnly]
    public class EmpleadosController : Controller
    {
        private RestauranteEntitiesContext db = new RestauranteEntitiesContext();

        // GET: Empleados
        public ActionResult Index()
        {
            var empleadoes = db.Empleadoes.Include(e => e.TipoEmpleado);
            return View(empleadoes.ToList());
        }

        // GET: Empleados/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleado empleado = db.Empleadoes.Find(id);
            if (empleado == null)
            {
                return HttpNotFound();
            }
            return View(empleado);
        }
        //Registrar_Personal
        public ActionResult Registrar_Personal()
        {
            ViewBag.IdTipoEmpleado = new SelectList(db.TipoEmpleadoes, "ID", "Descripcion");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Registrar_Personal([Bind(Include = "ID,Contraseña,IdTipoEmpleado,Nombre,Celular,Correo,Direccion,Sueldo")] Empleado empleado)
        {
            if (ModelState.IsValid)
            {
                empleado.Sueldo = 0;
                db.Empleadoes.Add(empleado);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdTipoEmpleado = new SelectList(db.TipoEmpleadoes, "ID", "Descripcion", empleado.IdTipoEmpleado);
            return View(empleado);
        }
        [AllowAnonymous]
        // GET: Empleados/Create
        public ActionResult Create()
        {
            ViewBag.IdTipoEmpleado = new SelectList(db.TipoEmpleadoes, "ID", "Descripcion");
            return View();
        }
        
        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Contraseña,IdTipoEmpleado,Nombre,Celular,Correo,Direccion,Sueldo")] Empleado empleado)
        {
            if (ModelState.IsValid)
            {
                empleado.Sueldo = 0;
                empleado.IdTipoEmpleado = 5;
                db.Empleadoes.Add(empleado);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            ViewBag.IdTipoEmpleado = new SelectList(db.TipoEmpleadoes, "ID", "Descripcion", empleado.IdTipoEmpleado);
            return View(empleado);
        }

        // GET: Empleados/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleado empleado = db.Empleadoes.Find(id);
            if (empleado == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdTipoEmpleado = new SelectList(db.TipoEmpleadoes, "ID", "Descripcion", empleado.IdTipoEmpleado);
            return View(empleado);
        }

        // POST: Empleados/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Contraseña,IdTipoEmpleado,Nombre,Celular,Correo,Direccion,Sueldo")] Empleado empleado)
        {
            if (ModelState.IsValid)
            {
                db.Entry(empleado).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdTipoEmpleado = new SelectList(db.TipoEmpleadoes, "ID", "Descripcion", empleado.IdTipoEmpleado);
            return View(empleado);
        }

        // GET: Empleados/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleado empleado = db.Empleadoes.Find(id);
            if (empleado == null)
            {
                return HttpNotFound();
            }
            return View(empleado);
        }

        // POST: Empleados/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Empleado empleado = db.Empleadoes.Find(id);
            db.Empleadoes.Remove(empleado);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        [AllowAnonymous]
        public ActionResult Login()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login([Bind(Include = "ID,Contraseña,IdTipoEmpleado,Nombre,Celular,Correo,Direccion,Sueldo")] Empleado user)
        {
            if (ModelState.IsValid)
            {
                var us = from u in db.Empleadoes.Include("TipoEmpleado")
                         where u.ID == user.ID && u.Contraseña == user.Contraseña
                         select u;
                Empleado user2 = us.FirstOrDefault();
                if (user2 != null)
                {
                    Session[SessionName.User] = user2;
                    if (user2.IdTipoEmpleado == 1)
                        return RedirectToAction("Index_Administrador", "Home");
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
                else
                {
                    ViewBag.ErrorMessage = "invalido ctv >:v";
                }


            }
            return View(user);
        }

        [AllowAnonymous]
        public ActionResult LogOff()
        {
            Session.Clear();
            return RedirectToAction("Index", "Home");
        }
        //Recuperar
        [AllowAnonymous]
        // GET: Empleados/Create
        public ActionResult Recuperar()
        {
            return View();
        }
        [AllowAnonymous]
        public void enviarEMail(string correo,string password)
        {
            MailMessage Correo = new MailMessage();
            Correo.From = new MailAddress("Correodelalucha@gmail.com");
            Correo.To.Add(correo);
            Correo.Subject=("Recuperar Contraseña La Lucha");
            Correo.Body = "Hola! Buen dia, Usted solicito recuperar su contraseña: " + password;
            Correo.Priority = MailPriority.Normal;

            SmtpClient ServerEmail = new SmtpClient();
            ServerEmail.Credentials = new NetworkCredential("Correodelalucha@gmail.com", "contraseñadelalucha");
            ServerEmail.Host = "smtp.gmail.com";
            ServerEmail.Port = 587;
            ServerEmail.EnableSsl = true;
            try
            {
                ServerEmail.Send(Correo);
            }
            catch (Exception e)
            {
                Console.Write(e);
            }
            Correo.Dispose();
        }
        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Recuperar([Bind(Include = "ID,Contraseña,IdTipoEmpleado,Nombre,Celular,Correo,Direccion,Sueldo")] Empleado empleado)
        {
            var us = from u in db.Empleadoes.Include("TipoEmpleado")
                     where u.Correo == empleado.Correo
                     select u;
            Empleado usuario = us.FirstOrDefault();
            enviarEMail(usuario.Correo, usuario.Contraseña);
            return RedirectToAction("Index", "Home");
        }

    }
}

La-Suela-Carrito-de-Compras-master/LaSuela_CodigoFuente/TrabajoFinalWeb/Views/Empleados/Create.cshtml
@model TrabajoFinalWeb.Models.Empleado

@{
    ViewBag.Title = "Create";
}

<body class="subpage">
    <h2>Nuevo Registro</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Contraseña, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Contraseña, new { htmlAttributes = new { @class = "form-control", type = "password" } })
                    @Html.ValidationMessageFor(model => model.Contraseña, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Correo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Correo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Correo, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Celular, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Celular, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Celular, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Registrarse" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
 </body>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

La-Suela-Carrito-de-Compras-master/LaSuela_CodigoFuente/TrabajoFinalWeb/Views/Empleados/Delete.cshtml
@model TrabajoFinalWeb.Models.Empleado

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout_Administrador.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Empleado</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Contraseña)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contraseña)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Celular)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Celular)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Correo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Correo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sueldo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sueldo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoEmpleado.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoEmpleado.Descripcion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

La-Suela-Carrito-de-Compras-master/LaSuela_CodigoFuente/TrabajoFinalWeb/Views/Empleados/Details.cshtml
@model TrabajoFinalWeb.Models.Empleado

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout_Administrador.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Empleado</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Contraseña)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contraseña)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Celular)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Celular)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Correo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Correo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sueldo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sueldo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoEmpleado.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoEmpleado.Descripcion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

La-Suela-Carrito-de-Compras-master/LaSuela_CodigoFuente/TrabajoFinalWeb/Views/Empleados/Edit.cshtml
@model TrabajoFinalWeb.Models.Empleado

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout_Administrador.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Empleado</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Contraseña, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contraseña, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contraseña, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdTipoEmpleado, "IdTipoEmpleado", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdTipoEmpleado", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdTipoEmpleado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Celular, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Celular, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Celular, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Correo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Correo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Correo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sueldo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sueldo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sueldo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

La-Suela-Carrito-de-Compras-master/LaSuela_CodigoFuente/TrabajoFinalWeb/Views/Empleados/Index.cshtml
@model IEnumerable<TrabajoFinalWeb.Models.Empleado>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_Administrador.cshtml";
}

<body class="subpage">
    <h2>Lista de Empleados</h2>

    <p>
        @Html.ActionLink("Registrar Nuevo Empleado", "Registrar_Personal")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contraseña)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Celular)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Correo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Direccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoEmpleado.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoEmpleado.Sueldo)
            </th>
            <th>
                Opciones
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Contraseña)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Celular)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Correo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Direccion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TipoEmpleado.Descripcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TipoEmpleado.Sueldo)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                </td>
            </tr>
        }

    </table>
</body>

La-Suela-Carrito-de-Compras-master/LaSuela_CodigoFuente/TrabajoFinalWeb/Views/Empleados/Login.cshtml
@model  TrabajoFinalWeb.Models.Empleado

@{
    ViewBag.Title = "Login";
}


<body class="subpage">
    <h2>Iniciar Sesion</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.ID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Contraseña, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Contraseña, new { htmlAttributes = new { @class = "form-control", type = "password" } })
                    @Html.ValidationMessageFor(model => model.Contraseña, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <div class="form-group">
                        <font color="red">
                            @ViewBag.ErrorMessage;
                        </font>
                    </div>
                    <input type="submit" value="Iniciar Sesion" class="btn btn-default" />
                </div>
            </div>
            @Html.ActionLink("¿Olvidaste tu contraseña?", "Recuperar","Empleados")
        </div>
    }
</body>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

La-Suela-Carrito-de-Compras-master/LaSuela_CodigoFuente/TrabajoFinalWeb/Views/Empleados/Recuperar.cshtml
@model TrabajoFinalWeb.Models.Empleado

<body class="subpage">
    <h2>Recuperar Contraseña</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })


            <div class="form-group">
                @Html.LabelFor(model => model.Correo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Correo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Correo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Enviar" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>