La-Suela-Carrito-de-Compras-master/LaSuela_CodigoFuente/TrabajoFinalWeb/Models/DetalleBoleta.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabajoFinalWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class DetalleBoleta
    {
        public int ID { get; set; }
        public int IdPedido { get; set; }
        [DisplayName("Monto Total")]
        public decimal MontoTotal { get; set; }
        public int IdModoDePago { get; set; }
    
        public virtual ModoDePago ModoDePago { get; set; }
        public virtual Pedido Pedido { get; set; }
    }
}

La-Suela-Carrito-de-Compras-master/LaSuela_CodigoFuente/TrabajoFinalWeb/Controllers/DetalleBoletasController.cs
using Gma.QrCodeNet.Encoding;
using Gma.QrCodeNet.Encoding.Windows.Render;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TrabajoFinalWeb.Models;
using System.Windows.Forms;
using Hotel_UPC.Authorization;
using Restaurante.Constantes;

namespace TrabajoFinalWeb.Controllers
{
    [UserLoggedOn]
    [AdminsOnly]
    public class DetalleBoletasController : Controller
    {
        private RestauranteEntitiesContext db = new RestauranteEntitiesContext();
        // GET: DetalleBoletas
        public ActionResult Index()
        {
            var detalleBoletas = db.DetalleBoletas.Include(d => d.ModoDePago).Include(d => d.Pedido);
            return View(detalleBoletas.ToList());
        }

        [AllowAnonymous]
        // GET: DetalleBoletas
        public ActionResult Index_Especifico()
        {
            int id_Pedido = (from c in db.Pedidoes select c).Count();
            var detalleBoletas = from c in db.DetalleBoletas where c.IdPedido == id_Pedido select c;
            return View(detalleBoletas.ToList());
        }
        
        public ActionResult generarCodigoQR(int? id)
        {
            //DetalleBoleta detalle = db.DetalleBoletas.Find(id);
            //var detalleBoletas = db.DetalleBoletas.Include(d => d.ModoDePago).Include(d => d.Pedido);
            //String monto = Convert.ToString(detalle.MontoTotal);
            //QRCodeEncoder encoder = new QRCodeEncoder();
            //Bitmap img = encoder.Encode(monto);
            //Image QR = (Image)img;
            //using (MemoryStream ms = new MemoryStream())
            //{
            //    QR.Save(ms, ImageFormat.Jpeg);
            //    byte[] imageBytes = ms.ToArray();
            //    ViewBag.Texto = "data:image/gif;base64" + Convert.ToBase64String(imageBytes);
            //}
            return RedirectToAction("Index_Especifico");
        }
        // GET: DetalleBoletas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DetalleBoleta detalleBoleta = db.DetalleBoletas.Find(id);
            if (detalleBoleta == null)
            {
                return HttpNotFound();
            }
            return View(detalleBoleta);
        }

        // GET: DetalleBoletas/Create
        public ActionResult Create()
        {
            ViewBag.IdModoDePago = new SelectList(db.ModoDePagoes, "ID", "Descripcion");
            ViewBag.IdPedido = new SelectList(db.Pedidoes, "ID", "Detalle");
            return View();
        }

        // POST: DetalleBoletas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,IdPedido,MontoTotal,IdModoDePago")] DetalleBoleta detalleBoleta)
        {
            if (ModelState.IsValid)
            {
                db.DetalleBoletas.Add(detalleBoleta);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdModoDePago = new SelectList(db.ModoDePagoes, "ID", "Descripcion", detalleBoleta.IdModoDePago);
            ViewBag.IdPedido = new SelectList(db.Pedidoes, "ID", "Detalle", detalleBoleta.IdPedido);
            return View(detalleBoleta);
        }

        // GET: DetalleBoletas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DetalleBoleta detalleBoleta = db.DetalleBoletas.Find(id);
            if (detalleBoleta == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdModoDePago = new SelectList(db.ModoDePagoes, "ID", "Descripcion", detalleBoleta.IdModoDePago);
            ViewBag.IdPedido = new SelectList(db.Pedidoes, "ID", "Detalle", detalleBoleta.IdPedido);
            return View(detalleBoleta);
        }

        // POST: DetalleBoletas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,IdPedido,MontoTotal,IdModoDePago")] DetalleBoleta detalleBoleta)
        {
            if (ModelState.IsValid)
            {
                db.Entry(detalleBoleta).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdModoDePago = new SelectList(db.ModoDePagoes, "ID", "Descripcion", detalleBoleta.IdModoDePago);
            ViewBag.IdPedido = new SelectList(db.Pedidoes, "ID", "Detalle", detalleBoleta.IdPedido);
            return View(detalleBoleta);
        }




        // GET: DetalleBoletas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DetalleBoleta detalleBoleta = db.DetalleBoletas.Find(id);
            if (detalleBoleta == null)
            {
                return HttpNotFound();
            }
            return View(detalleBoleta);
        }

        // POST: DetalleBoletas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DetalleBoleta detalleBoleta = db.DetalleBoletas.Find(id);
            db.DetalleBoletas.Remove(detalleBoleta);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        //Pedido_Boleta

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Pedido_Boleta()
        {
            int indice = (from c in db.PS select c).Count();
            ViewBag.MontoTotal = (from a in db.PPS.
                            Include("Producto").Include("P").AsEnumerable()
                                  where a.IdPedido == indice
                                  select a.Producto.Precio).Sum();
            ViewBag.IdModoDePago = new SelectList(db.ModoDePagoes, "ID", "Descripcion");
            return View();
        }
        //RegistrarPedido

        [AllowAnonymous]
        public IEnumerable<TrabajoFinalWeb.Models.P> Getpedidos()
        {
            return db.PS.AsEnumerable<TrabajoFinalWeb.Models.P>();
        }

        [AllowAnonymous]
        public IEnumerable<TrabajoFinalWeb.Models.PP> Getproducto_pedidos()
        {
            return db.PPS.AsEnumerable<TrabajoFinalWeb.Models.PP>();
        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RegistrarPedido(int IdModoDePago)
        {
            IEnumerable<TrabajoFinalWeb.Models.P> lista = Getpedidos();
            IEnumerable<TrabajoFinalWeb.Models.PP> listaPP = Getproducto_pedidos();

            Pedido pedido = new Pedido();
            Productos_Pedidos producto_pedido = new Productos_Pedidos();
            List<Productos_Pedidos> arreglo = new List<Productos_Pedidos>();
            Empleado objUser = (Empleado)Session[SessionName.User];
            for (int i = 0; i < db.PS.Count(); i++)
            {
                //pedido.ID = (int)lista.ElementAt(i).ID;
                pedido.Atendido = (bool)lista.ElementAt(i).Atendido;
                pedido.Detalle = objUser.Nombre;
                pedido.IdEmpleado = "ADMINMax";
            }
            db.Pedidoes.Add(pedido);
            db.SaveChanges();
            int id_Pedido= (from c in db.Pedidoes select c).Count();
            for (int i = 0; i < db.PPS.Count(); i++)
            {
                producto_pedido.IdPedido = id_Pedido;
                producto_pedido.IdProducto = (int)listaPP.ElementAt(i).IdProducto;
                db.Productos_Pedidos.Add(producto_pedido);
                db.SaveChanges();
            }
            DetalleBoleta detalle = new DetalleBoleta();
            detalle.IdModoDePago = IdModoDePago;
            detalle.IdPedido = id_Pedido;
            decimal montoTotal= (from a in db.Productos_Pedidos.
                              Include("Producto").Include("Pedido").AsEnumerable()
                             where a.IdPedido == id_Pedido
                             select a.Producto.Precio).Sum();
            detalle.MontoTotal = montoTotal;
            db.DetalleBoletas.Add(detalle);
            db.SaveChanges();
            db.eliminarTodo();
            db.SaveChanges();
            var detalleBoletas = db.DetalleBoletas.Include(d => d.ModoDePago).Include(d => d.Pedido);
            return RedirectToAction("Index_Especifico");
        }
    }
}

La-Suela-Carrito-de-Compras-master/LaSuela_CodigoFuente/TrabajoFinalWeb/Views/DetalleBoletas/Create.cshtml
@model TrabajoFinalWeb.Models.DetalleBoleta

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DetalleBoleta</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdPedido, "IdPedido", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdPedido", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdPedido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MontoTotal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MontoTotal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MontoTotal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdModoDePago, "IdModoDePago", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdModoDePago", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdModoDePago, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

La-Suela-Carrito-de-Compras-master/LaSuela_CodigoFuente/TrabajoFinalWeb/Views/DetalleBoletas/Delete.cshtml
@model TrabajoFinalWeb.Models.DetalleBoleta

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DetalleBoleta</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MontoTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MontoTotal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModoDePago.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModoDePago.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pedido.Detalle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pedido.Detalle)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

La-Suela-Carrito-de-Compras-master/LaSuela_CodigoFuente/TrabajoFinalWeb/Views/DetalleBoletas/Details.cshtml
@model TrabajoFinalWeb.Models.DetalleBoleta

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>DetalleBoleta</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MontoTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MontoTotal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModoDePago.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModoDePago.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pedido.Detalle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pedido.Detalle)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

La-Suela-Carrito-de-Compras-master/LaSuela_CodigoFuente/TrabajoFinalWeb/Views/DetalleBoletas/Edit.cshtml
@model TrabajoFinalWeb.Models.DetalleBoleta

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DetalleBoleta</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.IdPedido, "IdPedido", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdPedido", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdPedido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MontoTotal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MontoTotal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MontoTotal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdModoDePago, "IdModoDePago", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdModoDePago", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdModoDePago, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

La-Suela-Carrito-de-Compras-master/LaSuela_CodigoFuente/TrabajoFinalWeb/Views/DetalleBoletas/Index.cshtml
@model IEnumerable<TrabajoFinalWeb.Models.DetalleBoleta>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_Administrador.cshtml";
}
<body class="subpage">

    <h2>Todas las Boletas</h2>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MontoTotal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModoDePago.Descripcion)
            </th>
            <th>
                Nombre del Cliente
            </th>
            <th>Opciones</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MontoTotal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ModoDePago.Descripcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Pedido.Detalle)
                </td>
                <td>
                    @Html.ActionLink("Ver Detalle", "Details", new { id = item.ID }) 
                </td>
            </tr>
        }

    </table>
</body>

La-Suela-Carrito-de-Compras-master/LaSuela_CodigoFuente/TrabajoFinalWeb/Views/DetalleBoletas/Index_Especifico.cshtml
@model IEnumerable<TrabajoFinalWeb.Models.DetalleBoleta>

<body class="subpage">

    <h2>Pedido en Especifico</h2>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MontoTotal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModoDePago.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pedido.Detalle)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MontoTotal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ModoDePago.Descripcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Pedido.Detalle)
                </td>
            </tr>
        }
    </table>

</body>

La-Suela-Carrito-de-Compras-master/LaSuela_CodigoFuente/TrabajoFinalWeb/Views/DetalleBoletas/Pedido_Boleta.cshtml
@model TrabajoFinalWeb.Models.DetalleBoleta

<body class="subpage">
    <h2>Detalle de la Boleta</h2>
    @using (Html.BeginForm("RegistrarPedido", "DetalleBoletas", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Metodo de Pago </h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.IdModoDePago, "IdModoDePago", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("IdModoDePago", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IdModoDePago, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Siguiente" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }