La-Suela-Carrito-de-Compras-master/LaSuela_CodigoFuente/TrabajoFinalWeb/Models/Productos_Pedidos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabajoFinalWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Productos_Pedidos
    {
        public int ID { get; set; }
        public int IdProducto { get; set; }
        public int IdPedido { get; set; }
        [DisplayName("Anotaciones extras")]
        public string Observacion { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Pedido Pedido { get; set; }
    }
}

La-Suela-Carrito-de-Compras-master/LaSuela_CodigoFuente/TrabajoFinalWeb/Controllers/PPsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TrabajoFinalWeb.Models;

namespace TrabajoFinalWeb.Controllers
{
    public class PPsController : Controller
    {
        private RestauranteEntitiesContext db = new RestauranteEntitiesContext();

        // GET: PPs
        public ActionResult Index()
        {
            var pPS = db.PPS.Include(p => p.Producto);
            return View(pPS.ToList());
        }

        // GET: PPs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PP pP = db.PPS.Find(id);
            if (pP == null)
            {
                return HttpNotFound();
            }
            return View(pP);
        }

        // GET: PPs/Create
        public ActionResult Create()
        {
            ViewBag.IdProducto = new SelectList(db.Productoes, "ID", "Nombre");
            return View();
        }

        // POST: PPs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,IdProducto,IdPedido,Observacion")] PP pP)
        {
            if (ModelState.IsValid)
            {
                db.PPS.Add(pP);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdProducto = new SelectList(db.Productoes, "ID", "Nombre", pP.IdProducto);
            return View(pP);
        }

        // GET: PPs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PP pP = db.PPS.Find(id);
            if (pP == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdProducto = new SelectList(db.Productoes, "ID", "Nombre", pP.IdProducto);
            return View(pP);
        }

        // POST: PPs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,IdProducto,IdPedido,Observacion")] PP pP)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pP).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdProducto = new SelectList(db.Productoes, "ID", "Nombre", pP.IdProducto);
            return View(pP);
        }

        // GET: PPs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PP pP = db.PPS.Find(id);
            if (pP == null)
            {
                return HttpNotFound();
            }
            return View(pP);
        }

        // POST: PPs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PP pP = db.PPS.Find(id);
            db.PPS.Remove(pP);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

La-Suela-Carrito-de-Compras-master/LaSuela_CodigoFuente/TrabajoFinalWeb/Controllers/Productos_PedidosController.cs
using Hotel_UPC.Authorization;
using Restaurante.Constantes;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TrabajoFinalWeb.Models;

namespace TrabajoFinalWeb.Controllers
{
    [UserLoggedOn]
    public class Productos_PedidosController : Controller
    {
        private RestauranteEntitiesContext db = new RestauranteEntitiesContext();

        private void creacionPedido() //CrearNuevoPedido
        {
            //CrearNuevoPedido
            P objNuevoPedido = new P();
            objNuevoPedido.Atendido = false;
            db.PS.Add(objNuevoPedido);
            db.SaveChanges();
            //Pedido objNuevoPedido = new Pedido();
            //objNuevoPedido.Atendido = false;
            //objNuevoPedido.Detalle = txtNombreCliente.Text;
            //objNuevoPedido.IdEmpleado = "ADMINMax";
        }

        // GET: Productos_Pedidos
        public ActionResult Index()
        {
            var productos_Pedidos = db.Productos_Pedidos.Include(p => p.Pedido).Include(p => p.Producto);
            return View(productos_Pedidos.ToList());
        }

        // GET: Productos_Pedidos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Productos_Pedidos productos_Pedidos = db.Productos_Pedidos.Find(id);
            if (productos_Pedidos == null)
            {
                return HttpNotFound();
            }
            return View(productos_Pedidos);
        }

        // GET: Productos_Pedidos/Create
        public ActionResult Create()
        {
            ViewBag.IdPedido = new SelectList(db.Pedidoes, "ID", "Detalle");
            ViewBag.IdProducto = new SelectList(db.Productoes, "ID", "Nombre");
            return View();
        }

        // POST: Productos_Pedidos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,IdProducto,IdPedido,Observacion")] Productos_Pedidos productos_Pedidos)
        {
            if (ModelState.IsValid)
            {
                db.Productos_Pedidos.Add(productos_Pedidos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdPedido = new SelectList(db.Pedidoes, "ID", "Detalle", productos_Pedidos.IdPedido);
            ViewBag.IdProducto = new SelectList(db.Productoes, "ID", "Nombre", productos_Pedidos.IdProducto);
            return View(productos_Pedidos);
        }

        // GET: Productos_Pedidos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Productos_Pedidos productos_Pedidos = db.Productos_Pedidos.Find(id);
            if (productos_Pedidos == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdPedido = new SelectList(db.Pedidoes, "ID", "Detalle", productos_Pedidos.IdPedido);
            ViewBag.IdProducto = new SelectList(db.Productoes, "ID", "Nombre", productos_Pedidos.IdProducto);
            return View(productos_Pedidos);
        }

        // POST: Productos_Pedidos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,IdProducto,IdPedido,Observacion")] Productos_Pedidos productos_Pedidos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(productos_Pedidos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdPedido = new SelectList(db.Pedidoes, "ID", "Detalle", productos_Pedidos.IdPedido);
            ViewBag.IdProducto = new SelectList(db.Productoes, "ID", "Nombre", productos_Pedidos.IdProducto);
            return View(productos_Pedidos);
        }

        // GET: Productos_Pedidos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Productos_Pedidos productos_Pedidos = db.Productos_Pedidos.Find(id);
            if (productos_Pedidos == null)
            {
                return HttpNotFound();
            }
            return View(productos_Pedidos);
        }

        // POST: Productos_Pedidos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Productos_Pedidos productos_Pedidos = db.Productos_Pedidos.Find(id);
            db.Productos_Pedidos.Remove(productos_Pedidos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // GET: Productos_Pedidos/Create
        public ActionResult Orden()
        {
            int cont = 0;
            var lista_de_productos = from c in db.Productoes
                        select c;
            ViewBag.Productos = lista_de_productos.ToList();
            ViewBag.Contador = cont;
            Empleado objUser = (Empleado)Session[SessionName.User];
            ViewBag.Nombre =  objUser.Nombre;
            return View(new List<PP>());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Orden(int id,int ncontador)
        {
            //Producto producto = db.Productoes.Find(id);
            if (ncontador == 0)
            {
                creacionPedido();
                ncontador++;
            }
            PP aux = new PP();
            aux.IdProducto = id;
            aux.IdPedido = (from c in db.PS select c).Count();
            if (ModelState.IsValid)
            {
                db.PPS.Add(aux);
                db.SaveChanges();
            }
            //Productos
            var lista_de_productos = from c in db.Productoes
                                     select c;
            ViewBag.Productos = lista_de_productos.ToList();
            ViewBag.Contador = ncontador;

            return View(db.PPS.ToList());
        }
    }
}

La-Suela-Carrito-de-Compras-master/LaSuela_CodigoFuente/TrabajoFinalWeb/Views/Productos_Pedidos/Create.cshtml
@model TrabajoFinalWeb.Models.Productos_Pedidos

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Productos_Pedidos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdProducto, "IdProducto", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdProducto", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdProducto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdPedido, "IdPedido", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdPedido", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdPedido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Observacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Observacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Observacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

La-Suela-Carrito-de-Compras-master/LaSuela_CodigoFuente/TrabajoFinalWeb/Views/Productos_Pedidos/Delete.cshtml
@model TrabajoFinalWeb.Models.Productos_Pedidos

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Productos_Pedidos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Observacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Observacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pedido.Detalle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pedido.Detalle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Producto.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Producto.Nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

La-Suela-Carrito-de-Compras-master/LaSuela_CodigoFuente/TrabajoFinalWeb/Views/Productos_Pedidos/Details.cshtml
@model TrabajoFinalWeb.Models.Productos_Pedidos

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Productos_Pedidos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Observacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Observacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pedido.Detalle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pedido.Detalle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Producto.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Producto.Nombre)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

La-Suela-Carrito-de-Compras-master/LaSuela_CodigoFuente/TrabajoFinalWeb/Views/Productos_Pedidos/Edit.cshtml
@model TrabajoFinalWeb.Models.Productos_Pedidos

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Productos_Pedidos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.IdProducto, "IdProducto", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdProducto", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdProducto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdPedido, "IdPedido", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdPedido", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdPedido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Observacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Observacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Observacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

La-Suela-Carrito-de-Compras-master/LaSuela_CodigoFuente/TrabajoFinalWeb/Views/Productos_Pedidos/Index.cshtml
@model IEnumerable<TrabajoFinalWeb.Models.Productos_Pedidos>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Observacion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pedido.Detalle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Producto.Nombre)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Observacion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pedido.Detalle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Producto.Nombre)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

La-Suela-Carrito-de-Compras-master/LaSuela_CodigoFuente/TrabajoFinalWeb/Views/Productos_Pedidos/Orden.cshtml
@model IEnumerable<TrabajoFinalWeb.Models.PP>
@{
    List<TrabajoFinalWeb.Models.Producto> lista = ViewBag.Productos;
    int ncontador = ViewBag.Contador;
    string nombre = ViewBag.Nombre;
}


<body class="subpage">
    
    <div class="col-xs-12 col-sm-9">
        <h2>Bienvenido @nombre ! </h2>
        @* Hamburguesas*@
    <a name="tabla1"></a name="tabla1">
        <table class="table" >
            <tr>
                <th colspan="3" align="center">
                    Zapatos
                </th>
            </tr>
            @for (int i = 0; i < lista.Count(); i++)
            {
                <tr>
                    @if (lista[i].IdTipoProducto == 1)
                {
                        <td>
                            @using (Html.BeginForm("Orden", "Productos_Pedidos", FormMethod.Post))
                            {
                                @Html.AntiForgeryToken()
                                <input type="hidden" id="id" name="id" value=@lista[i].ID>
                                <input type="hidden" id="ncontador" name="ncontador" value=@ncontador>
                                <h5>Nombre:      @lista[i].Nombre</h5>
                                <p> Descripcion: @lista[i].Descripcion </p>
                                <p> Precio:      @lista[i].Precio </p>
                            <input type="submit" value="Agregar" class="btn btn-default" />
                                                      
                            }
                        </td>
                        <td>
                            <img src="~/images/@lista[i].imagen" alt="" width="213" height="194" />
                        </td>
                    }
                </tr>
            }
        </table>

        <a name="tabla2"></a>
        @* Complementos *@
        <table class="table">
            <tr>
                <th colspan="3" align="center">
                    Complementos
                </th>
            </tr>
            @for (int i = 0; i < lista.Count(); i++)
            {
                <tr>
                    @if (lista[i].IdTipoProducto == 2)
                    {
                        <td>
                            @using (Html.BeginForm("Orden", "Productos_Pedidos", FormMethod.Post))
                            {
                                @Html.AntiForgeryToken()
                                <input type="hidden" id="id" name="id" value=@lista[i].ID>
                                <input type="hidden" id="ncontador" name="ncontador" value=@ncontador>
                                <h5>Nombre:      @lista[i].Nombre</h5>
                                <p> Descripcion: @lista[i].Descripcion </p>
                                <p> Precio:      @lista[i].Precio </p>
                                <input type="submit" value="Agregar" class="btn btn-default" />

                            }
                        </td>
                        <td>
                            <img src="~/images/@lista[i].imagen" alt="" width="213" height="194" />
                        </td>
                    }
                </tr>
            }
        </table>
           
     <a name="tabla3"> </a>
        @* Combo *@
        <table class="table">
            <tr>
                <th colspan="3" align="center">
                    Combos
                </th>
            </tr>
            @for (int i = 0; i < lista.Count(); i++)
            {
                <tr>
                    @if (lista[i].IdTipoProducto == 3)
                    {
                        <td>
                            @using (Html.BeginForm("Orden", "Productos_Pedidos", FormMethod.Post))
                            {
                                @Html.AntiForgeryToken()
                                <input type="hidden" id="id" name="id" value=@lista[i].ID>
                                <input type="hidden" id="ncontador" name="ncontador" value=@ncontador>
                                <h5>Nombre:      @lista[i].Nombre</h5>
                                <p> Descripcion: @lista[i].Descripcion </p>
                                <p> Precio:      @lista[i].Precio </p>
                                <input type="submit" value="Agregar" class="btn btn-default" />

                            }
                        </td>
                        <td>
                            <img src="~/images/@lista[i].imagen" alt="" width="213" height="194" />
                        </td>
                    }
                </tr>
            }
        </table>
    </div><!--/.col-xs-12.col-sm-9-->

    <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar">
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Producto.Nombre)
                </th>
                <th>
                    Opciones
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>

                    <td>
                        @Html.DisplayFor(modelItem => item.Producto.Nombre)
                    </td>
                    <td>
                        @Html.ActionLink("Delete", "Delete", "PPs", new { id = item.ID }, new { id = item.ID })
                    </td>
                </tr>
            }
        </table>
        @using (Html.BeginForm("Pedido_Boleta", "DetalleBoletas", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <input type="submit" value="Siguiente" class="btn btn-default" />
        }
    </div><!--/.sidebar-offcanvas-->


</body>